### ISSUE TITLE
problem switching to daffy profile 

### ISSUE THREAD

**Issue by Omaehamoushindeiru** [duckietown/duckietown-shell#107]
briang@Brians-Air ~ % dts profile switch daffy          
                    ___  _   _  ___ _  _____ ___ _____ _____      ___  _     ___ _  _ ___ _    _    
                   |   \| | | |/ __| |/ /_ _| __|_   _/ _ \ \    / / \| |   / __| || | __| |  | |   
                   | |) | |_| | (__| ' < | || _|  | || (_) \ \/\/ /| .` |   \__ \ __ | _|| |__| |__ 
                   |___/ \___/ \___|_|\_\___|___| |_| \___/ \_/\_/ |_|\_|   |___/_||_|___|____|____|
                   _________________________________________________________________________________
                   Profile: daffy                                                            v6.0.17

+----------------------------------------------------------------------------------------------------------------------+
💬 An Autolab is a smart-city extension of any Duckietown. Autolabs can localize and communicate with Duckiebots. Learn more:

    https://cutt.ly/autolab-docs
+----------------------------------------------------------------------------------------------------------------------+
2024-08-08 15:40:52 Brians-Air.lan shell[21770] INFO Checking for updates for the command set 'duckietown'...
2024-08-08 15:40:52 Brians-Air.lan shell[21770] INFO Fetching remote SHA from github.com ...
2024-08-08 15:40:52 Brians-Air.lan shell[21770] INFO Installing dependencies for command set 'duckietown'...

dts :  Requirement already satisfied: pyyaml!=5.4.0,!=5.4.1,!=6.0.0,<7 in ./.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages (from -r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 4)) (6.0.1)
    :  Collecting netifaces-plus==0.12.2 (from -r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 7))
    :    Using cached netifaces_plus-0.12.2-cp39-cp39-macosx_11_0_arm64.whl.metadata (9.3 kB)
    :  Collecting docker==6.1.3 (from -r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 8))
    :    Using cached docker-6.1.3-py3-none-any.whl.metadata (3.5 kB)
    :  Collecting docker-compose==1.29.2 (from -r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 9))
    :    Using cached docker_compose-1.29.2-py2.py3-none-any.whl.metadata (4.7 kB)
    :  Collecting GitPython==3.1.37 (from -r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 10))
    :    Using cached GitPython-3.1.37-py3-none-any.whl.metadata (12 kB)
    :  Collecting python-dateutil==2.8.2 (from -r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 11))
    :    Using cached python_dateutil-2.8.2-py2.py3-none-any.whl.metadata (8.2 kB)
    :  Collecting pytz==2023.3 (from -r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 12))
    :    Using cached pytz-2023.3-py2.py3-none-any.whl.metadata (22 kB)
    :  Collecting zeroconf==0.122.0 (from -r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 13))
    :    Using cached zeroconf-0.122.0-cp39-cp39-macosx_14_0_arm64.whl
    :  Collecting dockertown==0.2.5 (from -r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 16))
    :    Using cached dockertown-0.2.5-py3-none-any.whl
    :  Collecting duckietown-docker-utils-daffy==6.1.1 (from -r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 17))
    :    Using cached duckietown_docker_utils_daffy-6.1.1-py3-none-any.whl
    :  Collecting packaging>=14.0 (from docker==6.1.3->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 8))
    :    Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
    :  Requirement already satisfied: requests>=2.26.0 in ./.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages (from docker==6.1.3->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 8)) (2.31.0)
    :  Requirement already satisfied: urllib3>=1.26.0 in ./.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages (from docker==6.1.3->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 8)) (2.2.2)
    :  Collecting websocket-client>=0.32.0 (from docker==6.1.3->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 8))
    :    Using cached websocket_client-1.8.0-py3-none-any.whl.metadata (8.0 kB)
    :  Collecting pyyaml!=5.4.0,!=5.4.1,!=6.0.0,<7 (from -r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 4))
    :    Using cached PyYAML-5.3.1.tar.gz (269 kB)
    :    Preparing metadata (setup.py): started
    :    Preparing metadata (setup.py): finished with status 'done'
    :  Collecting distro<2,>=1.5.0 (from docker-compose==1.29.2->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 9))
    :    Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
    :  Collecting dockerpty<1,>=0.4.1 (from docker-compose==1.29.2->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 9))
    :    Using cached dockerpty-0.4.1-py3-none-any.whl
    :  Collecting docopt<1,>=0.6.1 (from docker-compose==1.29.2->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 9))
    :    Using cached docopt-0.6.2-py2.py3-none-any.whl
    :  Collecting jsonschema<4,>=2.5.1 (from docker-compose==1.29.2->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 9))
    :    Using cached jsonschema-3.2.0-py2.py3-none-any.whl.metadata (7.8 kB)
    :  Collecting python-dotenv<1,>=0.13.0 (from docker-compose==1.29.2->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 9))
    :    Using cached python_dotenv-0.21.1-py3-none-any.whl.metadata (21 kB)
    :  Collecting texttable<2,>=0.9.0 (from docker-compose==1.29.2->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 9))
    :    Using cached texttable-1.7.0-py2.py3-none-any.whl.metadata (9.8 kB)
    :  Collecting websocket-client>=0.32.0 (from docker==6.1.3->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 8))
    :    Using cached websocket_client-0.59.0-py2.py3-none-any.whl.metadata (6.5 kB)
    :  Collecting gitdb<5,>=4.0.1 (from GitPython==3.1.37->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 10))
    :    Using cached gitdb-4.0.11-py3-none-any.whl.metadata (1.2 kB)
    :  Requirement already satisfied: six>=1.5 in ./.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages (from python-dateutil==2.8.2->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 11)) (1.16.0)
    :  Collecting async-timeout>=3.0.0 (from zeroconf==0.122.0->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 13))
    :    Using cached async_timeout-4.0.3-py3-none-any.whl.metadata (4.2 kB)
    :  Collecting ifaddr>=0.1.7 (from zeroconf==0.122.0->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 13))
    :    Using cached ifaddr-0.2.0-py3-none-any.whl.metadata (4.9 kB)
    :  Requirement already satisfied: pydantic<2,>=1.5 in ./.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages (from dockertown==0.2.5->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 16)) (1.10.17)
    :  Requirement already satisfied: tqdm in ./.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages (from dockertown==0.2.5->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 16)) (4.66.5)
    :  Requirement already satisfied: typer>=0.4.1 in ./.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages (from dockertown==0.2.5->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 16)) (0.12.3)
    :  Requirement already satisfied: typing-extensions in ./.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages (from dockertown==0.2.5->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 16)) (4.12.2)
    :  Requirement already satisfied: humanfriendly in ./.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages (from dockertown==0.2.5->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 16)) (10.0)
    :  Collecting progressbar2 (from duckietown-docker-utils-daffy==6.1.1->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 17))
    :    Using cached progressbar2-4.4.2-py3-none-any.whl.metadata (17 kB)
    :  Collecting paramiko>=2.4.3 (from docker[ssh]>=5->docker-compose==1.29.2->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 9))
    :    Using cached paramiko-3.4.0-py3-none-any.whl.metadata (4.4 kB)
    :  Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->GitPython==3.1.37->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 10))
    :    Using cached smmap-5.0.1-py3-none-any.whl.metadata (4.3 kB)
    :  Collecting attrs>=17.4.0 (from jsonschema<4,>=2.5.1->docker-compose==1.29.2->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 9))
    :    Using cached attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
    :  Collecting pyrsistent>=0.14.0 (from jsonschema<4,>=2.5.1->docker-compose==1.29.2->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 9))
    :    Using cached pyrsistent-0.20.0-cp39-cp39-macosx_10_9_universal2.whl.metadata (27 kB)
    :  Requirement already satisfied: setuptools in ./.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages (from jsonschema<4,>=2.5.1->docker-compose==1.29.2->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 9)) (72.1.0)
    :  Requirement already satisfied: charset-normalizer<4,>=2 in ./.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages (from requests>=2.26.0->docker==6.1.3->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 8)) (3.3.2)
    :  Requirement already satisfied: idna<4,>=2.5 in ./.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages (from requests>=2.26.0->docker==6.1.3->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 8)) (3.7)
    :  Requirement already satisfied: certifi>=2017.4.17 in ./.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages (from requests>=2.26.0->docker==6.1.3->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 8)) (2024.7.4)
    :  Requirement already satisfied: click>=8.0.0 in ./.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages (from typer>=0.4.1->dockertown==0.2.5->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 16)) (8.1.7)
    :  Requirement already satisfied: shellingham>=1.3.0 in ./.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages (from typer>=0.4.1->dockertown==0.2.5->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 16)) (1.5.4)
    :  Requirement already satisfied: rich>=10.11.0 in ./.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages (from typer>=0.4.1->dockertown==0.2.5->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 16)) (13.7.1)
    :  Collecting python-utils>=3.8.1 (from progressbar2->duckietown-docker-utils-daffy==6.1.1->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 17))
    :    Using cached python_utils-3.8.2-py2.py3-none-any.whl.metadata (9.7 kB)
    :  Collecting bcrypt>=3.2 (from paramiko>=2.4.3->docker[ssh]>=5->docker-compose==1.29.2->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 9))
    :    Using cached bcrypt-4.2.0-cp39-abi3-macosx_10_12_universal2.whl.metadata (9.6 kB)
    :  Collecting cryptography>=3.3 (from paramiko>=2.4.3->docker[ssh]>=5->docker-compose==1.29.2->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 9))
    :    Using cached cryptography-43.0.0-cp39-abi3-macosx_10_9_universal2.whl.metadata (5.4 kB)
    :  Collecting pynacl>=1.5 (from paramiko>=2.4.3->docker[ssh]>=5->docker-compose==1.29.2->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 9))
    :    Using cached PyNaCl-1.5.0-cp36-abi3-macosx_10_10_universal2.whl.metadata (8.7 kB)
    :  Requirement already satisfied: markdown-it-py>=2.2.0 in ./.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages (from rich>=10.11.0->typer>=0.4.1->dockertown==0.2.5->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 16)) (3.0.0)
    :  Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages (from rich>=10.11.0->typer>=0.4.1->dockertown==0.2.5->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 16)) (2.18.0)
    :  Collecting cffi>=1.12 (from cryptography>=3.3->paramiko>=2.4.3->docker[ssh]>=5->docker-compose==1.29.2->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 9))
    :    Using cached cffi-1.17.0-cp39-cp39-macosx_11_0_arm64.whl.metadata (1.5 kB)
    :  Requirement already satisfied: mdurl~=0.1 in ./.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer>=0.4.1->dockertown==0.2.5->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 16)) (0.1.2)
    :  Collecting pycparser (from cffi>=1.12->cryptography>=3.3->paramiko>=2.4.3->docker[ssh]>=5->docker-compose==1.29.2->-r /Users/briang/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt (line 9))
    :    Using cached pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
    :  Using cached netifaces_plus-0.12.2-cp39-cp39-macosx_11_0_arm64.whl (14 kB)
    :  Using cached docker-6.1.3-py3-none-any.whl (148 kB)
    :  Using cached docker_compose-1.29.2-py2.py3-none-any.whl (114 kB)
    :  Using cached GitPython-3.1.37-py3-none-any.whl (190 kB)
    :  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
    :  Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
    :  Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
    :  Using cached distro-1.9.0-py3-none-any.whl (20 kB)
    :  Using cached gitdb-4.0.11-py3-none-any.whl (62 kB)
    :  Using cached ifaddr-0.2.0-py3-none-any.whl (12 kB)
    :  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
    :  Using cached packaging-24.1-py3-none-any.whl (53 kB)
    :  Using cached python_dotenv-0.21.1-py3-none-any.whl (19 kB)
    :  Using cached texttable-1.7.0-py2.py3-none-any.whl (10 kB)
    :  Using cached websocket_client-0.59.0-py2.py3-none-any.whl (67 kB)
    :  Using cached progressbar2-4.4.2-py3-none-any.whl (56 kB)
    :  Using cached attrs-24.2.0-py3-none-any.whl (63 kB)
    :  Using cached paramiko-3.4.0-py3-none-any.whl (225 kB)
    :  Using cached pyrsistent-0.20.0-cp39-cp39-macosx_10_9_universal2.whl (83 kB)
    :  Using cached python_utils-3.8.2-py2.py3-none-any.whl (27 kB)
    :  Using cached smmap-5.0.1-py3-none-any.whl (24 kB)
    :  Using cached bcrypt-4.2.0-cp39-abi3-macosx_10_12_universal2.whl (472 kB)
    :  Using cached cryptography-43.0.0-cp39-abi3-macosx_10_9_universal2.whl (6.2 MB)
    :  Using cached PyNaCl-1.5.0-cp36-abi3-macosx_10_10_universal2.whl (349 kB)
    :  Using cached cffi-1.17.0-cp39-cp39-macosx_11_0_arm64.whl (178 kB)
    :  Using cached pycparser-2.22-py3-none-any.whl (117 kB)
    :  Building wheels for collected packages: pyyaml
    :    Building wheel for pyyaml (setup.py): started
    :    Building wheel for pyyaml (setup.py): finished with status 'error'
    :    error: subprocess-exited-with-error
    :    
    :    × python setup.py bdist_wheel did not run successfully.
    :    │ exit code: 1
    :    ╰─> [50 lines of output]
    :        warning: build_py: byte-compiling is disabled, skipping.
    :        
    :        Traceback (most recent call last):
    :          File "<string>", line 2, in <module>
    :          File "<pip-setuptools-caller>", line 34, in <module>
    :          File "/private/tmp/pip-install-lfsh5efr/pyyaml_9dc64ba78e724f6d89e07e33a32baeda/setup.py", line 291, in <module>
    :            setup(
    :          File "/Users/briang/.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
    :            return run_commands(dist)
    :          File "/Users/briang/.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    :            dist.run_commands()
    :          File "/Users/briang/.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
    :            self.run_command(cmd)
    :          File "/Users/briang/.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages/setuptools/dist.py", line 945, in run_command
    :            super().run_command(command)
    :          File "/Users/briang/.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    :            cmd_obj.run()
    :          File "/Users/briang/.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages/wheel/_bdist_wheel.py", line 378, in run
    :            self.run_command("build")
    :          File "/Users/briang/.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    :            self.distribution.run_command(command)
    :          File "/Users/briang/.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages/setuptools/dist.py", line 945, in run_command
    :            super().run_command(command)
    :          File "/Users/briang/.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    :            cmd_obj.run()
    :          File "/Users/briang/.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    :            self.run_command(cmd_name)
    :          File "/Users/briang/.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    :            self.distribution.run_command(command)
    :          File "/Users/briang/.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages/setuptools/dist.py", line 945, in run_command
    :            super().run_command(command)
    :          File "/Users/briang/.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    :            cmd_obj.run()
    :          File "/private/tmp/pip-install-lfsh5efr/pyyaml_9dc64ba78e724f6d89e07e33a32baeda/setup.py", line 185, in run
    :            _build_ext.run(self)
    :          File "/Users/briang/.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 329, in run
    :            customize_compiler(self.compiler)
    :          File "/Users/briang/.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages/setuptools/_distutils/sysconfig.py", line 299, in customize_compiler
    :            _customize_macos()
    :          File "/Users/briang/.duckietown/shell/profiles/daffy/venv/lib/python3.9/site-packages/setuptools/_distutils/sysconfig.py", line 285, in _customize_macos
    :            sys.platform == "darwin" and __import__('_osx_support').customize_compiler(
    :          File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/_osx_support.py", line 519, in customize_compiler
    :            _find_appropriate_compiler(_config_vars)
    :          File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/_osx_support.py", line 236, in _find_appropriate_compiler
    :            if not _find_executable(cc):
    :          File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/_osx_support.py", line 36, in _find_executable
    :            path = os.environ['PATH']
    :          File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/os.py", line 679, in __getitem__
    :            raise KeyError(key) from None
    :        KeyError: 'PATH'
    :        [end of output]
    :    
    :    note: This error originates from a subprocess, and is likely not a problem with pip.
    :    ERROR: Failed building wheel for pyyaml
    :    Running setup.py clean for pyyaml
    :  Failed to build pyyaml
    :  ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pyyaml)
    :  
2024-08-08 15:40:56 Brians-Air.lan shell[21770] ERROR An error occurred, the reason for the error should be printed above.

**Comment by HoldenGs** [comment]
I had this same issue. I worked around it by commenting out the requirement for PyYAML in the file `~/.duckietown/shell/profiles/daffy/commands/duckietown/__command_set__/requirements.txt` since I already had PyYAML installed
