### ISSUE TITLE
Incompatible with Python 3?

### ISSUE THREAD

**Issue by breandan** [duckietown/duckietown-shell#14]
There is [a dependency](https://github.com/duckietown/duckietown-shell/blob/6add7d4dfcfa8aa301303fac32e51d34eede879e/setup.py#L32) on [SystemCmd](https://github.com/AndreaCensi/system_cmd), which does not appear to be Python 3 compatible.

```
$ sudo pip install --no-cache-dir -U duckietown-shell
Collecting duckietown-shell
  Downloading https://files.pythonhosted.org/packages/a4/46/75531bfa685b2bc3669eecd5e891584c0da55e96abbc015baeb0188df52b/duckietown-shell-0.2.34.tar.gz (89kB)
    100% |████████████████████████████████| 92kB 2.1MB/s 
Collecting GitPython (from duckietown-shell)
  Downloading https://files.pythonhosted.org/packages/fe/e5/fafe827507644c32d6dc553a1c435cdf882e0c28918a5bab29f7fbebfb70/GitPython-2.1.11-py2.py3-none-any.whl (448kB)
    100% |████████████████████████████████| 450kB 2.6MB/s 
Collecting PyContracts (from duckietown-shell)
  Downloading https://files.pythonhosted.org/packages/16/f7/06a3fc92758cf288b9e0d09b0d0f18eff39970214775505d85c002277721/PyContracts-1.8.3.tar.gz (90kB)
    100% |████████████████████████████████| 92kB 3.6MB/s 
Requirement already up-to-date: PyYAML in /home/breandan/.local/lib/python3.6/site-packages (from duckietown-shell)
Collecting SystemCmd (from duckietown-shell)
  Downloading https://files.pythonhosted.org/packages/49/28/ec21be30ee9b7061e6b01f596f98e649ac08a0d2333c60b39dae24a8efc0/SystemCmd-2.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qb0g7xmt/SystemCmd/setup.py", line 19, in <module>
        version = get_version(filename='src/system_cmd/__init__.py')
      File "/tmp/pip-build-qb0g7xmt/SystemCmd/setup.py", line 8, in get_version
        with file(filename) as f:
    NameError: name 'file' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qb0g7xmt/SystemCmd/
```

Pip version: `pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)`

**Comment by AndreaCensi** [comment]
I think it now might be compatible, or very little work needed.

**Comment by AndreaCensi** [comment]
supposedly compatible with Python 3 now
