### ISSUE TITLE
Failure on Ubuntu16: pip install --upgrade pip

### ISSUE THREAD

**Issue by datahaki** [duckietown/duckietown-shell#24]
```
datahaki@datahaki-N501JW:~$ pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
  Rolling back uninstall of pip
Exception:
Traceback (most recent call last):
  File "/home/datahaki/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/datahaki/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/datahaki/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/datahaki/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/datahaki/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/datahaki/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/datahaki/.local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/datahaki/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pip-18.1.dist-info'
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

```

**Comment by AndreaCensi** [comment]
where is this step in the instructions?

**Comment by datahaki** [comment]
https://www.youtube.com/watch?v=t2g538NLx_w

**Comment by AndreaCensi** [comment]
you are doing Ubuntu 18 and Ubuntu 16?

**Comment by AndreaCensi** [comment]
@datahaki can you delete `~/.dt-shell/commands` and try again?
it might be in an inconsistent state.

**Comment by datahaki** [comment]
https://github.com/duckietown/duckietown-shell/commit/6868299b26d39571b09cba6e15eada8707913031
