### ISSUE TITLE
ERROR:dts:write() argument must be str, not bytes

### ISSUE THREAD

**Issue by breandan** [duckietown/duckietown-shell#36]
This is [the line](https://github.com/duckietown/duckietown-shell-commands/blob/9dc413fedb50cd2230ec4751a82b7639df3bbead/challenges/evaluator/command.py#L190) in question. Seems like a Python 2/3 issue. Not sure why it installs to `python3.6` as I explicitly installed with the [pip2 installation instructions](https://github.com/duckietown/duckietown-shell#installation-on-ubuntu-18xx):

```
dts :  Traceback (most recent call last):
    :    File "/home/breandan/.local/lib/python3.6/site-packages/dt_shell/__init__.py", line 38, in cli_main
    :      cli_main_()
    :    File "/home/breandan/.local/lib/python3.6/site-packages/dt_shell/__init__.py", line 106, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python3.6/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/breandan/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 409, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/breandan/.local/lib/python3.6/site-packages/dt_shell/dt_command_abs.py", line 41, in do_command
    :      cls.commands[word].do_command(cls.commands[word], shell, ' '.join(parts[1:]))
    :    File "/home/breandan/.local/lib/python3.6/site-packages/dt_shell/dt_command_abs.py", line 52, in do_command
    :      cls.command(shell, args)
    :    File "/home/breandan/.dt-shell/commands/challenges/evaluator/command.py", line 190, in command
    :      logs += c
    :  TypeError: must be str, not bytes

dts :  Please report that you are using:
    :  
    :  duckietown-shell: 3.0.30
    :  duckietown-shell-commands: 1.0.14
    :  python: "3.6.6 (default, Sep 12 2018, 18:26:19) \n[GCC 8.0.1 20180414 (experimental)\
    :    \ [trunk revision 259383]]"
```

**Comment by AndreaCensi** [comment]
@breandan you are running the Python 3 version

It is still a bug.

It might have been solved in commands v1.0.15.
