### ISSUE TITLE
dts challenges submit -- SSLError: ('The read operation timed out',)

### ISSUE THREAD

**Issue by lavoiems** [duckietown/duckietown-shell#37]
When trying to submit a challenge, I get the following stacktrace after pushing the repository:

`dts :  Traceback (most recent call last):
    :    File "/usr/lib/python2.7/site-packages/dt_shell/__init__.py", line 38, in cli_main
    :      cli_main_()
    :    File "/usr/lib/python2.7/site-packages/dt_shell/__init__.py", line 106, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    :      return func(arg)
    :    File "/usr/lib/python2.7/site-packages/dt_shell/cli.py", line 409, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/usr/lib/python2.7/site-packages/dt_shell/dt_command_abs.py", line 41, in do_command
    :      cls.commands[word].do_command(cls.commands[word], shell, ' '.join(parts[1:]))
    :    File "/usr/lib/python2.7/site-packages/dt_shell/dt_command_abs.py", line 52, in do_command
    :      cls.command(shell, args)
    :    File "/root/.dt-shell/commands/challenges/submit/command.py", line 161, in command
    :      submission_id = dtserver_submit(token, sub_info.challenge_name, data)
    :    File "/usr/lib/python2.7/site-packages/dt_shell/remote.py", line 145, in dtserver_submit
    :      return make_server_request(token, endpoint, data=data, method=method)
    :    File "/usr/lib/python2.7/site-packages/dt_shell/remote.py", line 80, in make_server_request
    :      res = urllib.request.urlopen(req, timeout=timeout)
    :    File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    :      return opener.open(url, data, timeout)
    :    File "/usr/lib/python2.7/urllib2.py", line 429, in open
    :      response = self._open(req, data)
    :    File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    :      '_open', req)
    :    File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    :      result = func(*args)
    :    File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    :      context=self._context)
    :    File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    :      r = h.getresponse(buffering=True)
    :    File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    :      response.begin()
    :    File "/usr/lib/python2.7/httplib.py", line 438, in begin
    :      version, status, reason = self._read_status()
    :    File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
    :      line = self.fp.readline(_MAXLINE + 1)
    :    File "/usr/lib/python2.7/socket.py", line 480, in readline
    :      data = self._sock.recv(self._rbufsize)
    :    File "/usr/lib/python2.7/ssl.py", line 772, in recv
    :      return self.read(buflen)
    :    File "/usr/lib/python2.7/ssl.py", line 659, in read
    :      v = self._sslobj.read(len)
    :  SSLError: ('The read operation timed out',)

dts :  Please report that you are using:
    :  
    :  duckietown-shell: 3.0.30
    :  duckietown-shell-commands: 1.0.15
    :  python: "2.7.15 (default, Aug 16 2018, 14:17:09) \n[GCC 6.4.0]"
`

I am on OSX 10.14.

**Comment by lavoiems** [comment]
I get a similar error when running `dts challenges evaluate`. The stacktrace is slightly different:

DEBUG:dts:Monitoring container local-evaluator
INFO:dts:status: running
INFO:dt-challenges-runner:dt-challenges-runner 3.1.52
INFO:dts:duckietown-shell 3.0.30
INFO:duckietown-challenges:duckietown-challenges 3.2.12
DEBUG:runner-local:Running in directory /Users/Sam/Documents/playground/challenge-aido1_LF1-template-pytorch
DEBUG:dts:Checking docker environment for user root
WARNING:dts:No group docker defined.
ERROR:runner-local:Traceback (most recent call last):
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 35, in runner_local_main
    runner_local_main_()
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 93, in runner_local_main_
    result = get_challenge_description(token, subinfo.challenge_name)
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 189, in get_challenge_description
    return make_server_request(token, endpoint, data=data, method=method)
  File "/project/src/duckietown-shell/lib/dt_shell/remote.py", line 80, in make_server_request
    res = urllib.request.urlopen(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 772, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 659, in read
    v = self._sslobj.read(len)
SSLError: ('The read operation timed out',)

DEBUG:dts:monitoring graceful exit

**Comment by yunyunc** [comment]
I am having the same issue:

```
INFO:dts:status: running
INFO:dt-challenges-runner:dt-challenges-runner 3.1.52
INFO:dts:duckietown-shell 3.0.30
INFO:duckietown-challenges:duckietown-challenges 3.2.12
DEBUG:runner-local:Running in directory /Users/chenyun/challenge-aido1_luck-template-python
DEBUG:dts:Checking docker environment for user chenyun
WARNING:dts:No group docker defined.
ERROR:runner-local:Traceback (most recent call last):
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 35, in runner_local_main
    runner_local_main_()
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 93, in runner_local_main_
    result = get_challenge_description(token, subinfo.challenge_name)
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 189, in get_challenge_description
    return make_server_request(token, endpoint, data=data, method=method)
  File "/project/src/duckietown-shell/lib/dt_shell/remote.py", line 80, in make_server_request
    res = urllib.request.urlopen(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 772, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 659, in read
    v = self._sslobj.read(len)
SSLError: ('The read operation timed out',)
```

**Comment by takeitallsource** [comment]
Dear all, we are having problems with the submission server atm, it is down. We will post an update once it is back online.

**Comment by lavoiems** [comment]
Thank you for the update @takeitallsource . Is `dts challenges evaluate` related to the submission server?

**Comment by takeitallsource** [comment]
Yes, it downloads the challenge metadata from the submission server.

**Comment by lavoiems** [comment]
I see. Can we get an update when the issue is resolved?

**Comment by AndreaCensi** [comment]
@lavoiems looks like the server is more healthy now. Do you see improvements?

**Comment by lavoiems** [comment]
Yes, it seems resolved. I can close the issue. Thank you
