### ISSUE TITLE
Failed to reflash the sd card

### ISSUE THREAD

**Issue by Petrolkopf** [duckietown/duckietown-shell#39]
? This will erase the selected drive. Are you sure? Yes
Unexpected token x in JSON at position 1775

dts :  Traceback (most recent call last):
    :    File "/home/dieselkopf/.local/lib/python2.7/site-packages/dt_shell/__init__.py", line 38, in cli_main
    :      cli_main_()
    :    File "/home/dieselkopf/.local/lib/python2.7/site-packages/dt_shell/__init__.py", line 106, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    :      return func(arg)
    :    File "/home/dieselkopf/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 409, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/dieselkopf/.local/lib/python2.7/site-packages/dt_shell/dt_command_abs.py", line 47, in do_command
    :      cls.command(shell, args)
    :    File "/home/dieselkopf/.dt-shell/commands/init_sd_card/command.py", line 190, in command
    :      step2function[step_name](shell, parsed)
    :    File "/home/dieselkopf/.dt-shell/commands/init_sd_card/command.py", line 267, in step_flash
    :      raise Exception(msg)
    :  Exception: An error occurred while initializing the SD card, please check and try again (1).

dts :  Please report that you are using:
    :  
    :  duckietown-shell: 3.0.31
    :  duckietown-shell-commands: 1.1.1
    :  python: "2.7.12 (default, Nov 12 2018, 14:36:49) \n[GCC 5.4.0 20160609]"

**Comment by hzy5000** [comment]
I had the same problem. Just change the etcher version from 1.4.6 to 1.4.4 in the ~/.dt-shell/commands/init_sd_card/init_sd_card2.sh, then the problem will be solved.
