### ISSUE TITLE
Unable to Transfer a Submission to Real Duckie

### ISSUE THREAD

**Issue by heyt0ny** [duckietown/duckietown-shell#40]
Hello I've done all the steps in duckiebot preparation, including all calibrations. On both  duckiebot and host computer I have `/data/config/calibrations/kinematics/default.yaml`. But when I run `dts duckiebot evaluate robot-name --image image-name` - I get the following error:

```
Duckietown Shell commands version 1.1.1
INFO:dts:slim remote already running on duckiebot, restarting...
WARNING:dts:Container <Container: a375b5bb79> not found to remove! 409 Client Error: Conflict ("removal of container a375b5bb7927f306442bde71bf748b1f68a4c1fc50a9a9094e1ab165879da4c9 is already in progress")
INFO:dts:Getting calibration files
default.yaml                                                                                                                                                                     100%  265   354.6KB/s   00:00    
duckiebot.yaml                                                                                                                                                                   100%  268   391.8KB/s   00:00    
default.yaml                                                                                                                                                                     100%  668     1.0MB/s   00:00    
duckiebot.yaml                                                                                                                                                                   100%  665   947.8KB/s   00:00    
default.yaml                                                                                                                                                                     100%   68    77.0KB/s   00:00    
INFO:dts:/tmp/fake-tony-home/config/calibrations/camera_instrisic/duckiebot.yaml

dts :  Traceback (most recent call last):
    :    File "/home/tony/.local/lib/python2.7/site-packages/dt_shell/__init__.py", line 38, in cli_main
    :      cli_main_()
    :    File "/home/tony/.local/lib/python2.7/site-packages/dt_shell/__init__.py", line 106, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    :      return func(arg)
    :    File "/home/tony/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 409, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/tony/.local/lib/python2.7/site-packages/dt_shell/dt_command_abs.py", line 42, in do_command
    :      cls.commands[word].do_command(cls.commands[word], shell, ' '.join(parts[1:]))
    :    File "/home/tony/.local/lib/python2.7/site-packages/dt_shell/dt_command_abs.py", line 47, in do_command
    :      cls.command(shell, args)
    :    File "/home/tony/.dt-shell/commands/duckiebot/evaluate/command.py", line 54, in command
    :      volumes = setup_expected_volumes(parsed.hostname)
    :    File "/home/tony/.dt-shell/commands/duckiebot/evaluate/command.py", line 108, in setup_expected_volumes
    :      get_calibration_files(dir_fake_home_host, hostname)
    :    File "/home/tony/.dt-shell/commands/duckiebot/evaluate/command.py", line 137, in get_calibration_files
    :      tmp_dir + '/config/calibrations/kinematics/default.yaml')
    :  OSError: [Errno 2] No such file or directory

dts :  Please report that you are using:
    :  
    :  duckietown-shell: 3.0.31
    :  duckietown-shell-commands: 1.1.1
    :  python: "2.7.15rc1 (default, Nov 12 2018, 14:31:15) \n[GCC 7.3.0]"

```

What can I do about that?

**Comment by liampaull** [comment]
I'm pretty sure you just didn't put a kinematics calibration on your real robot so it's missing. Follow the instructions here: http://docs.duckietown.org/DT18/opmanual_duckiebot/out/wheel_calibration.html

**Comment by heyt0ny** [comment]
Thank you. It solved th eproblem!
