### ISSUE TITLE
duckietown-shell seems to require python 3.6 or higher

### ISSUE THREAD

**Issue by jzilly** [duckietown/duckietown-shell#44]
When running dts from either python 2.7 or 3.5 the following error appears since Python 3.6 types are used. Should the duckietown-shell from now on be installed from a virtual environment?

```
Cannot load command class 'challenges.info.command.DTCommand' (package='challenges.', command='info'): Traceback (most recent call last):
  File "/home/idscadmin/.local/lib/python3.5/site-packages/dt_shell/cli.py", line 376, in _load_commands
    klass = _load_class(spec)
  File "/home/idscadmin/.local/lib/python3.5/site-packages/dt_shell/cli.py", line 479, in _load_class
    mod = __import__(components[0])
  File "/home/idscadmin/.dt-shell/commands/challenges/__init__.py", line 2, in <module>
    from .define import *
  File "/home/idscadmin/.dt-shell/commands/challenges/define/__init__.py", line 1, in <module>
    from .command import *
  File "/home/idscadmin/.dt-shell/commands/challenges/define/command.py", line 10, in <module>
    from dt_shell.remote import make_server_request
  File "/home/idscadmin/.local/lib/python3.5/site-packages/dt_shell/remote.py", line 87
    data_read: bytes = res.read()
             ^
SyntaxError: invalid syntax


            !   To recover, you might want to delete the directory
            !
            !      ~/.dt-shell/commands
            !
            ! 
```

**Comment by afdaniele** [comment]
JIRA: https://ethidsc.atlassian.net/browse/DTSW-155

**Comment by AndreaCensi** [comment]
It does require 3.6. 
Now it gives a better message.
