### ISSUE TITLE
Flashing doesnt work anymore

### ISSUE THREAD

**Issue by AmaurX** [duckietown/duckietown-shell#47]
@AndreaCensi We are currently in the process of reflashing all our watchtowers. However, every goes well until this point : 
```INFO:dts:Considering copying /tmp/duckietown/docker_images/DT18_00_basic-9b17a420.tar.gz of size 0.021 GB

dts :  Traceback (most recent call last):
    :    File "/home/amaury/.local/lib/python3.7/site-packages/dt_shell/__init__.py", line 45, in cli_main
    :      cli_main_()
    :    File "/home/amaury/.local/lib/python3.7/site-packages/dt_shell/__init__.py", line 116, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/amaury/.local/lib/python3.7/site-packages/dt_shell/cli.py", line 409, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/amaury/.local/lib/python3.7/site-packages/dt_shell/dt_command_abs.py", line 47, in do_command
    :      cls.command(shell, args)
    :    File "/home/amaury/.dt-shell/commands/init_sd_card/command.py", line 191, in command
    :      step2function[step_name](shell, parsed)
    :    File "/home/amaury/.dt-shell/commands/init_sd_card/command.py", line 449, in step_setup
    :      configure_images(parsed, user_data, add_file_local, add_file)
    :    File "/home/amaury/.dt-shell/commands/init_sd_card/command.py", line 535, in configure_images
    :      available = psutil.disk_usage(TMP_ROOT_MOUNTPOINT).free
    :    File "/home/amaury/.local/lib/python3.7/site-packages/psutil/__init__.py", line 2106, in disk_usage
    :      return _psplatform.disk_usage(path)
    :    File "/home/amaury/.local/lib/python3.7/site-packages/psutil/_psposix.py", line 131, in disk_usage
    :      st = os.statvfs(path)
    :  FileNotFoundError: [Errno 2] No such file or directory: '/media/amaury/root'

dts :  Please report that you are using:
    :  
    :  duckietown-shell-commands: 4.0.5
    :  python: "3.7.3 (default, Mar 30 2019, 15:09:56) \n[GCC 5.4.0 20160609]"
    :  duckietown-shell: 4.0.12
```

I am using ubuntu16, python3.7 is from homebrew (as can be seen on the first lines of the errors)

**Comment by AndreaCensi** [comment]
What command are you running exactly?
Can you include the complete output?
If /media/amaury/root does not exist I would expect and earlier step to fail.

@liampaull FYI

**Comment by AmaurX** [comment]
command is : 
```dts init_sd_card --hostname watchtowernotconfigured --linux-username mom --linux-password MomWatches --wifi duckietown_backup:quackquack --country CH --compress```

output : 
```
INFO:dts:duckietown-shell 4.0.12

dts :  Problems with a command?
    :  
    :  Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :  Troubleshooting:
    :  
    :  - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :  - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :    (Note: you will have to re-configure.)
Duckietown Shell commands version 4.0.5
INFO:duckietown-challenges:duckietown-challenges 4.0.11
INFO:dts:Detected duckietown-challenges 4.0.11 


## Tips and tricks

### Multiple networks

    dts init_sd_card --wifi  network1:password1,network2:password2 --country US



### Steps

Without arguments the script performs the steps:

    flash
    expand
    mount
    setup
    unmount

You can use --steps to run only some of those:

    dts init_sd_card --steps expand,mount



    
DEBUG:dts:Checking docker environment for user amaury
DEBUG:dts:Found 'wget' at /usr/bin/wget
DEBUG:dts:Found 'tar' at /bin/tar
DEBUG:dts:Found 'udisksctl' at /usr/bin/udisksctl
DEBUG:dts:Found 'docker' at /usr/bin/docker
DEBUG:dts:Found 'base64' at /usr/bin/base64
DEBUG:dts:Found 'gzip' at /bin/gzip
DEBUG:dts:Found 'udevadm' at /sbin/udevadm
DEBUG:dts:Found 'lsblk' at /bin/lsblk
INFO:dts:Please type the device with your SD card. Please be careful to pick the right device and to include '/dev/'. Here's a list of the devices on your system:
Running /bin/bash /home/amaury/.dt-shell/commands/init_sd_card/list_disks.sh
NAME             TYPE   SIZE VENDOR
/dev/nvme0n1     disk   477G 
/dev/sda         disk    15G Generic 
Done!
Type the name of your device (include the '/dev' part):   /dev/sda
Running /bin/bash /home/amaury/.dt-shell/commands/init_sd_card/init_sd_card2.sh
64-bit OS detected...
Prior etcher-cli install detected at /tmp/duckietown/etcher-cli, skipping...
HypriotOS image was previously downloaded to /tmp/duckietown/hypriotos-rpi-v1.9.0.img.zip, skipping...
Flashing Hypriot image /tmp/duckietown/hypriotos-rpi-v1.9.0.img.zip to disk /dev/sda
? This will erase the selected drive. Are you sure? Yes
Flashing: 9.96 MB/s [========================] 100% eta 0s   
Validating: 0 B/s [========================] 100% eta 0s     

Checksums:
  - /dev/sda: 3ab3f1eb0b0b4e04f9630035ba95f26046b9e104a65dd78f8bb4fa9ed24c0dbebc647e8aa119c0b60bd8ba4d28e739709befbdfceac45ec2416b53c1b0f93423
Flashing Hypriot image succeeded.
Done!
DEBUG:dts:Found 'parted' at /sbin/parted
DEBUG:dts:Found 'resize2fs' at /sbin/resize2fs
DEBUG:dts:Found 'df' at /bin/df
DEBUG:dts:Found 'umount' at /bin/umount
INFO:dts:Found device /dev/sda.
INFO:dts:Current status:
DEBUG:dts:$ ['sudo', 'lsblk', '/dev/sda']
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    1   15G  0 disk 
├─sda2   8:2    1  935M  0 part 
└─sda1   8:1    1   64M  0 part 
DEBUG:dts:$ ['sudo', 'parted', '-s', '/dev/sda', 'resizepart', '2', '100%']
DEBUG:dts:$ ['sudo', 'e2fsck', '-f', '/dev/sda2']
e2fsck 1.42.13 (17-May-2015)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
root: 30693/239360 files (0.2% non-contiguous), 217214/239359 blocks
DEBUG:dts:$ ['sudo', 'resize2fs', '/dev/sda2']
resize2fs 1.42.13 (17-May-2015)
Resizing the filesystem on /dev/sda2 to 3915520 (4k) blocks.
The filesystem on /dev/sda2 is now 3915520 (4k) blocks long.

INFO:dts:Updated status:
DEBUG:dts:$ ['sudo', 'lsblk', '/dev/sda']
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda      8:0    1  15G  0 disk 
├─sda2   8:2    1  15G  0 part 
└─sda1   8:1    1  64M  0 part 
DEBUG:dts:$ ['sudo', 'udevadm', 'trigger']
DEBUG:dts:$ ['udisksctl', 'mount', '-b', '/dev/disk/by-label/HypriotOS']
Mounted /dev/sda1 at /media/amaury/HypriotOS.
DEBUG:dts:$ ['sudo', 'udevadm', 'trigger']
DEBUG:dts:$ ['udisksctl', 'mount', '-b', '/dev/disk/by-label/root']
Mounted /dev/sda2 at /media/amaury/root.
/home/amaury/.dt-shell/commands/init_sd_card/command.py:348: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  user_data = yaml.load(open(user_data_file).read())
INFO:dts:Adding file /home/mom/.ssh/authorized_keys
INFO:dts:Adding file /home/mom/.dt-shell/config
INFO:dts:Adding file /secrets/tokens/dt1
INFO:dts:Adding file /data/stats/init_sd_card/README.txt
INFO:dts:Adding file /data/stats/init_sd_card/CHANGELOG
INFO:dts:Adding file /data/stats/init_sd_card/version
INFO:dts:Adding file /data/stats/init_sd_card/flash_time
INFO:dts:Adding file /data/stats/init_sd_card/flash_user
INFO:dts:Adding file /data/stats/init_sd_card/flash_machine
INFO:dts:Adding file /data/stats/init_sd_card/parameters/hostname
INFO:dts:Adding file /data/stats/init_sd_card/parameters/linux_username
INFO:dts:Adding file /data/stats/init_sd_card/parameters/stacks_to_run
INFO:dts:Adding file /data/stats/init_sd_card/parameters/stacks_to_load
INFO:dts:Adding file /data/stats/init_sd_card/parameters/compress
INFO:dts:Adding file /data/stats/init_sd_card/parameters/device
INFO:dts:Adding file /data/stats/init_sd_card/parameters/country
INFO:dts:Adding file /data/stats/init_sd_card/parameters/wifi
INFO:dts:Adding file /data/stats/init_sd_card/parameters/ethz_username
INFO:dts:Adding file /data/stats/MAC/README.txt
INFO:dts:Configuration already found in ~/.ssh/config
INFO:dts:Adding file /var/local/wificfg.json
INFO:dts:Adding file /etc/wpa_supplicant/wpa_supplicant.conf
INFO:dts:Stacks to load: ['DT18_00_basic', 'DT18_01_health_stats', 'DT18_02_others', 'DT18_05_duckiebot_base']
INFO:dts:Stacks to run: ['DT18_00_basic', 'DT18_01_health_stats']
DEBUG:dts:$ ['docker-compose', '-f', '/home/amaury/.dt-shell/commands/init_sd_card/stacks/DT18_00_basic.yaml', 'config', '--quiet']
INFO:dts:Adding file /var/local/DT18_00_basic.yaml
DEBUG:dts:$ ['docker-compose', '-f', '/home/amaury/.dt-shell/commands/init_sd_card/stacks/DT18_01_health_stats.yaml', 'config', '--quiet']
INFO:dts:Adding file /var/local/DT18_01_health_stats.yaml
DEBUG:dts:$ ['docker-compose', '-f', '/home/amaury/.dt-shell/commands/init_sd_card/stacks/DT18_02_others.yaml', 'config', '--quiet']
INFO:dts:Adding file /var/local/DT18_02_others.yaml
DEBUG:dts:$ ['docker-compose', '-f', '/home/amaury/.dt-shell/commands/init_sd_card/stacks/DT18_05_duckiebot_base.yaml', 'config', '--quiet']
INFO:dts:Adding file /var/local/DT18_05_duckiebot_base.yaml
INFO:dts:The stacks that are available are: DT18_01_health_stats, DT18_02_others, DT18_03_roscore, DT18_05_duckiebot_base, DT18_04_camera, DT18_99_swarm, DT18_00_basic
INFO:dts:You asked to use ['DT18_00_basic', 'DT18_01_health_stats', 'DT18_02_others', 'DT18_05_duckiebot_base']
/home/amaury/.dt-shell/commands/init_sd_card/command.py:925: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  stacks2yaml[sn] = yaml.load(open(lpath).read())
DEBUG:dts:Checking docker environment for user amaury
INFO:dts:Pulling portainer/portainer:linux-arm
DEBUG:dts:$ ['docker', 'pull', 'portainer/portainer:linux-arm']
linux-arm: Pulling from portainer/portainer
Digest: sha256:7cfcb6c26595207f6f2a5a12895fd3b4dd6b38d4081e0c3cb63008a3bf8fb1de
Status: Image is up to date for portainer/portainer:linux-arm
INFO:dts:Pulling v2tec/watchtower:armhf-latest
DEBUG:dts:$ ['docker', 'pull', 'v2tec/watchtower:armhf-latest']
armhf-latest: Pulling from v2tec/watchtower
Digest: sha256:63abf3fc71a46b8fc46674342766d976e6a97d6c70d2560a0986ec63c1784812
Status: Image is up to date for v2tec/watchtower:armhf-latest
INFO:dts:Using cached file /tmp/duckietown/docker_images/DT18_00_basic-9b17a420.tar.gz
INFO:dts:Pulling duckietown/rpi-simple-server:master18
DEBUG:dts:$ ['docker', 'pull', 'duckietown/rpi-simple-server:master18']
master18: Pulling from duckietown/rpi-simple-server
Digest: sha256:6b6787319cd87b413d5b0a8737f6127c719293c12936c94b5ea3a2d7fd62f6b5
Status: Image is up to date for duckietown/rpi-simple-server:master18
INFO:dts:Pulling duckietown/rpi-health:master18
DEBUG:dts:$ ['docker', 'pull', 'duckietown/rpi-health:master18']
master18: Pulling from duckietown/rpi-health
Digest: sha256:f56a664e610813be5e99a05e9afb78629f424323ad825afc0f19f92acf9c3a61
Status: Image is up to date for duckietown/rpi-health:master18
INFO:dts:Pulling duckietown/rpi-duckiebot-online:master18
DEBUG:dts:$ ['docker', 'pull', 'duckietown/rpi-duckiebot-online:master18']
master18: Pulling from duckietown/rpi-duckiebot-online
Digest: sha256:68e5d5b1d6677e8f0110b4f81bb1fb3d47d5658d8de8988108999b7cd8dce3e2
Status: Image is up to date for duckietown/rpi-duckiebot-online:master18
INFO:dts:Pulling duckietown/rpi-duckiebot-loader:master18
DEBUG:dts:$ ['docker', 'pull', 'duckietown/rpi-duckiebot-loader:master18']
master18: Pulling from duckietown/rpi-duckiebot-loader
Digest: sha256:986708fcac2f9051b17f51c02514279a42089e758b220311ac2de52aa5bad1ec
Status: Image is up to date for duckietown/rpi-duckiebot-loader:master18
INFO:dts:Using cached file /tmp/duckietown/docker_images/DT18_01_health_stats-83f5dbad.tar.gz
INFO:dts:Pulling duckietown/rpi-python-picamera:master18
DEBUG:dts:$ ['docker', 'pull', 'duckietown/rpi-python-picamera:master18']
master18: Pulling from duckietown/rpi-python-picamera
Digest: sha256:56e72af27a01611f2e5b693e87a6361db470c0aced17fa509e64328139713b8c
Status: Image is up to date for duckietown/rpi-python-picamera:master18
INFO:dts:Using cached file /tmp/duckietown/docker_images/DT18_02_others-3f233b14.tar.gz
INFO:dts:Pulling arm32v7/ros:kinetic-ros-base-xenial
DEBUG:dts:$ ['docker', 'pull', 'arm32v7/ros:kinetic-ros-base-xenial']
kinetic-ros-base-xenial: Pulling from arm32v7/ros
Digest: sha256:a72fa9bafc7e0309ae85bc490f26e43f260a75afae39bf2b76749c7502c2b5d8
Status: Image is up to date for arm32v7/ros:kinetic-ros-base-xenial
INFO:dts:Pulling duckietown/rpi-ros-kinetic-base:master19
DEBUG:dts:$ ['docker', 'pull', 'duckietown/rpi-ros-kinetic-base:master19']
master19: Pulling from duckietown/rpi-ros-kinetic-base
Digest: sha256:0ac02150a0102a1d90b2d7730b9b4bc6029cd153ded13a9dc910cd10ea232af1
Status: Image is up to date for duckietown/rpi-ros-kinetic-base:master19
INFO:dts:Pulling duckietown/rpi-ros-kinetic-roscore:master18
DEBUG:dts:$ ['docker', 'pull', 'duckietown/rpi-ros-kinetic-roscore:master18']
master18: Pulling from duckietown/rpi-ros-kinetic-roscore
Digest: sha256:4a4427b7cf2a74e3042590abf6ae5ae33cae4c8f632e62e2969931d6488f6dec
Status: Image is up to date for duckietown/rpi-ros-kinetic-roscore:master18
INFO:dts:Pulling duckietown/duckiebot-interface:master19
DEBUG:dts:$ ['docker', 'pull', 'duckietown/duckiebot-interface:master19']
master19: Pulling from duckietown/duckiebot-interface
Digest: sha256:15ceaccbc14054d384a6c6ee90e9144a6dc88d5026fad614f87ed9d0c176476b
Status: Image is up to date for duckietown/duckiebot-interface:master19
INFO:dts:Pulling duckietown/rpi-duckiebot-base:master19
DEBUG:dts:$ ['docker', 'pull', 'duckietown/rpi-duckiebot-base:master19']
master19: Pulling from duckietown/rpi-duckiebot-base
Digest: sha256:22cbeacc64d3057313027a13f862d04776425cf84eb1358ee9c915a128917d13
Status: Image is up to date for duckietown/rpi-duckiebot-base:master19
INFO:dts:Pulling duckietown/rpi-duckiebot-ros-picam:master18
DEBUG:dts:$ ['docker', 'pull', 'duckietown/rpi-duckiebot-ros-picam:master18']
master18: Pulling from duckietown/rpi-duckiebot-ros-picam
Digest: sha256:69b269e561f17ae1d0e44b8a48fcfd877e3794bb74683d68467034cecd6676b1
Status: Image is up to date for duckietown/rpi-duckiebot-ros-picam:master18
INFO:dts:Pulling duckietown/rpi-duckiebot-web_video_server:master18
DEBUG:dts:$ ['docker', 'pull', 'duckietown/rpi-duckiebot-web_video_server:master18']
master18: Pulling from duckietown/rpi-duckiebot-web_video_server
Digest: sha256:a431258052de46d0450f9aa5e36f935368a5ca297d9a0b1351790e77e43d8a9b
Status: Image is up to date for duckietown/rpi-duckiebot-web_video_server:master18
INFO:dts:Pulling duckietown/rpi-duckiebot-logger:master18
DEBUG:dts:$ ['docker', 'pull', 'duckietown/rpi-duckiebot-logger:master18']
master18: Pulling from duckietown/rpi-duckiebot-logger
Digest: sha256:e66c1c82dfbe7f6b4a5f3532138e6cc6a6a7f8e01ff92cdad35fb5f3a2eec8e0
Status: Image is up to date for duckietown/rpi-duckiebot-logger:master18
INFO:dts:Using cached file /tmp/duckietown/docker_images/DT18_05_duckiebot_base-5a26660a.tar.gz
DEBUG:dts:{'DT18_00_basic': StackInfo(archive='/tmp/duckietown/docker_images/DT18_00_basic-9b17a420.tar.gz', image_name2id={'portainer/portainer:linux-arm': 'sha256:30e5c1f30c6f3c49b05130dc0b38b432d77b7e34974a7b160c946d81824d676d', 'v2tec/watchtower:armhf-latest': 'sha256:b74a792de471c9652fb9456071f207eec88cd39dfb17d883d9b755ade5a40d24'}, hname='9b17a420'), 'DT18_01_health_stats': StackInfo(archive='/tmp/duckietown/docker_images/DT18_01_health_stats-83f5dbad.tar.gz', image_name2id={'duckietown/rpi-simple-server:master18': 'sha256:fe4f149c3646cacc9bffe3d8ec524b32a212ce48b217871d65f273476b88edbe', 'duckietown/rpi-health:master18': 'sha256:8b7e75c76852e9db87ab14f12c1cd589e7e752e027084ccd7d4d00190a33fef4', 'duckietown/rpi-duckiebot-online:master18': 'sha256:2784311b814c9c1016dc7dcec83ec31e98f8566e02c46ebd3abd328dccde0217', 'duckietown/rpi-duckiebot-loader:master18': 'sha256:034be85761ff8f455e69e276b8fc1bdb62e670dbaf41ef1c288b1d9984e97393'}, hname='83f5dbad'), 'DT18_02_others': StackInfo(archive='/tmp/duckietown/docker_images/DT18_02_others-3f233b14.tar.gz', image_name2id={'duckietown/rpi-python-picamera:master18': 'sha256:29cbbdc1158f8ed02dffa272013c8e51f2463299de6140fbef804dad69690ec0'}, hname='3f233b14'), 'DT18_05_duckiebot_base': StackInfo(archive='/tmp/duckietown/docker_images/DT18_05_duckiebot_base-5a26660a.tar.gz', image_name2id={'arm32v7/ros:kinetic-ros-base-xenial': 'sha256:c68166d57464f0f9753c6ad0e158970850194778aed0dc9402df71f4cf927c10', 'duckietown/rpi-ros-kinetic-base:master19': 'sha256:9d3f01e18aef0bb7a87dd441695e57b2d920e51ff9afb11fd7ef3f283f688ba7', 'duckietown/rpi-ros-kinetic-roscore:master18': 'sha256:bbd55ea58fed4494aba597826c2d60565151ea48adcac941198baeee0de7c45f', 'duckietown/duckiebot-interface:master19': 'sha256:68342e84bfa8a51c791bda0401698fcbe9c3ea1ec64278b65050fcb59f189204', 'duckietown/rpi-duckiebot-base:master19': 'sha256:9264ff0ee60cc91c80d50ef32be7b6ee0095f9578855a1a278c76b6be1d602fa', 'duckietown/rpi-duckiebot-ros-picam:master18': 'sha256:c66216ca5f4969ff0fdf8193bc63283fc500f637e724c531c48c7034733786fa', 'duckietown/rpi-duckiebot-web_video_server:master18': 'sha256:1abedec62fb5c4323896461bb5ed4e05ab6b82e60655966f90b0eee1d0860ce4', 'duckietown/rpi-duckiebot-logger:master18': 'sha256:e02c1b982b9b0b3c34360ceb35aed9996c3070554a97f4de04141dd574b0c89f'}, hname='5a26660a')}
INFO:dts:Considering copying /tmp/duckietown/docker_images/DT18_00_basic-9b17a420.tar.gz of size 0.021 GB

dts :  Traceback (most recent call last):
    :    File "/home/amaury/.local/lib/python3.7/site-packages/dt_shell/__init__.py", line 45, in cli_main
    :      cli_main_()
    :    File "/home/amaury/.local/lib/python3.7/site-packages/dt_shell/__init__.py", line 116, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/amaury/.local/lib/python3.7/site-packages/dt_shell/cli.py", line 409, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/amaury/.local/lib/python3.7/site-packages/dt_shell/dt_command_abs.py", line 47, in do_command
    :      cls.command(shell, args)
    :    File "/home/amaury/.dt-shell/commands/init_sd_card/command.py", line 191, in command
    :      step2function[step_name](shell, parsed)
    :    File "/home/amaury/.dt-shell/commands/init_sd_card/command.py", line 449, in step_setup
    :      configure_images(parsed, user_data, add_file_local, add_file)
    :    File "/home/amaury/.dt-shell/commands/init_sd_card/command.py", line 535, in configure_images
    :      available = psutil.disk_usage(TMP_ROOT_MOUNTPOINT).free
    :    File "/home/amaury/.local/lib/python3.7/site-packages/psutil/__init__.py", line 2106, in disk_usage
    :      return _psplatform.disk_usage(path)
    :    File "/home/amaury/.local/lib/python3.7/site-packages/psutil/_psposix.py", line 131, in disk_usage
    :      st = os.statvfs(path)
    :  FileNotFoundError: [Errno 2] No such file or directory: '/media/amaury/root'

dts :  Please report that you are using:
    :  
    :  duckietown-shell-commands: 4.0.5
    :  python: "3.7.3 (default, Mar 30 2019, 15:09:56) \n[GCC 5.4.0 20160609]"
    :  duckietown-shell: 4.0.12
```

**Comment by liampaull** [comment]
I successfully burned an SD card within the last hour

**Comment by AmaurX** [comment]
@liampaull could this be a ubuntu16 issue again?

**Comment by AndreaCensi** [comment]
Yes likely ubuntu16 does not mount the folders like in ubuntu18.

Does /media/amaury/root exist?
If not where does it mount it?

**Comment by AmaurX** [comment]
It does not exist. You wanna know where the sd card is mounted right? I can only see that while running the init_sd_card ?

**Comment by AmaurX** [comment]
actually when I put the sd card in adnd open the folders, /media/amaury/root does exist. Maybe at some point it unmounts before finishing?

**Comment by AmaurX** [comment]
I just tried again, having a watch command on /media/amaury, and the two folder (hypriotos and root) disappeared around when this line `master18: Pulling from duckietown/rpi-duckiebot-loader` appended.
Then now, the scripts seems to continue working beyond the previously crashing point

**Comment by AmaurX** [comment]
any ideas?

**Comment by AndreaCensi** [comment]
@AmaurX I think this is about ubuntu 16 - (and particularly your configuration of ubuntu 16).
I would just use ubuntu 18.

**Comment by AmaurX** [comment]
@AndreaCensi I just passed to clean ubuntu18. I followed exact instructions, I run into the exact same issue...

It pull all containers, then : 
```INFO:dts:Saving to /tmp/duckietown/docker_images/DT18_05_duckiebot_base-872d4931.tar
DEBUG:dts:$ ['docker', 'save', '-o', '/tmp/duckietown/docker_images/DT18_05_duckiebot_base-872d4931.tar', 'sha256:c68166d57464f0f9753c6ad0e158970850194778aed0dc9402df71f4cf927c10', 'sha256:9d3f01e18aef0bb7a87dd441695e57b2d920e51ff9afb11fd7ef3f283f688ba7', 'sha256:bbd55ea58fed4494aba597826c2d60565151ea48adcac941198baeee0de7c45f', 'sha256:f7077f9ab4d4cb6d3989a4aba60c9ae5400da3b77bb846d601338618a97379fa', 'sha256:f9bae971a2750cbe325902a4745242e210e203d5e59eab149546a527d733d57c', 'sha256:ed0ac1bdb45ecbc9ed262e6b95dcf2c6007084479f6f7ccbdf733ac5e2c01fd4', 'sha256:b061cddd7acedb54b058c4cf060b85f5351ec032fdce0beb6b70a085daaba48b', 'sha256:e02c1b982b9b0b3c34360ceb35aed9996c3070554a97f4de04141dd574b0c89f']
DEBUG:dts:$ ['gzip', '-f', '/tmp/duckietown/docker_images/DT18_05_duckiebot_base-872d4931.tar']
INFO:dts:Saved archive /tmp/duckietown/docker_images/DT18_05_duckiebot_base-872d4931.tar.gz of size 2.892 GB
DEBUG:dts:{'DT18_00_basic': StackInfo(archive='/tmp/duckietown/docker_images/DT18_00_basic-9b17a420.tar.gz', image_name2id={'portainer/portainer:linux-arm': 'sha256:30e5c1f30c6f3c49b05130dc0b38b432d77b7e34974a7b160c946d81824d676d', 'v2tec/watchtower:armhf-latest': 'sha256:b74a792de471c9652fb9456071f207eec88cd39dfb17d883d9b755ade5a40d24'}, hname='9b17a420'), 'DT18_01_health_stats': StackInfo(archive='/tmp/duckietown/docker_images/DT18_01_health_stats-83f5dbad.tar.gz', image_name2id={'duckietown/rpi-simple-server:master18': 'sha256:fe4f149c3646cacc9bffe3d8ec524b32a212ce48b217871d65f273476b88edbe', 'duckietown/rpi-health:master18': 'sha256:8b7e75c76852e9db87ab14f12c1cd589e7e752e027084ccd7d4d00190a33fef4', 'duckietown/rpi-duckiebot-online:master18': 'sha256:2784311b814c9c1016dc7dcec83ec31e98f8566e02c46ebd3abd328dccde0217', 'duckietown/rpi-duckiebot-loader:master18': 'sha256:034be85761ff8f455e69e276b8fc1bdb62e670dbaf41ef1c288b1d9984e97393'}, hname='83f5dbad'), 'DT18_02_others': StackInfo(archive='/tmp/duckietown/docker_images/DT18_02_others-3f233b14.tar.gz', image_name2id={'duckietown/rpi-python-picamera:master18': 'sha256:29cbbdc1158f8ed02dffa272013c8e51f2463299de6140fbef804dad69690ec0'}, hname='3f233b14'), 'DT18_05_duckiebot_base': StackInfo(archive='/tmp/duckietown/docker_images/DT18_05_duckiebot_base-872d4931.tar.gz', image_name2id={'arm32v7/ros:kinetic-ros-base-xenial': 'sha256:c68166d57464f0f9753c6ad0e158970850194778aed0dc9402df71f4cf927c10', 'duckietown/rpi-ros-kinetic-base:master19': 'sha256:9d3f01e18aef0bb7a87dd441695e57b2d920e51ff9afb11fd7ef3f283f688ba7', 'duckietown/rpi-ros-kinetic-roscore:master18': 'sha256:bbd55ea58fed4494aba597826c2d60565151ea48adcac941198baeee0de7c45f', 'duckietown/duckiebot-interface:master19': 'sha256:f7077f9ab4d4cb6d3989a4aba60c9ae5400da3b77bb846d601338618a97379fa', 'duckietown/rpi-duckiebot-base:master19': 'sha256:f9bae971a2750cbe325902a4745242e210e203d5e59eab149546a527d733d57c', 'duckietown/rpi-duckiebot-ros-picam:master18': 'sha256:ed0ac1bdb45ecbc9ed262e6b95dcf2c6007084479f6f7ccbdf733ac5e2c01fd4', 'duckietown/rpi-duckiebot-web_video_server:master18': 'sha256:b061cddd7acedb54b058c4cf060b85f5351ec032fdce0beb6b70a085daaba48b', 'duckietown/rpi-duckiebot-logger:master18': 'sha256:e02c1b982b9b0b3c34360ceb35aed9996c3070554a97f4de04141dd574b0c89f'}, hname='872d4931')}
INFO:dts:Considering copying /tmp/duckietown/docker_images/DT18_00_basic-9b17a420.tar.gz of size 0.021 GB

dts :  Traceback (most recent call last):
    :    File "/home/amaury/.local/lib/python3.6/site-packages/dt_shell/__init__.py", line 45, in cli_main
    :      cli_main_()
    :    File "/home/amaury/.local/lib/python3.6/site-packages/dt_shell/__init__.py", line 116, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python3.6/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/amaury/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 409, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/amaury/.local/lib/python3.6/site-packages/dt_shell/dt_command_abs.py", line 47, in do_command
    :      cls.command(shell, args)
    :    File "/home/amaury/.dt-shell/commands/init_sd_card/command.py", line 195, in command
    :      step2function[step_name](shell, parsed)
    :    File "/home/amaury/.dt-shell/commands/init_sd_card/command.py", line 454, in step_setup
    :      configure_images(parsed, user_data, add_file_local, add_file)
    :    File "/home/amaury/.dt-shell/commands/init_sd_card/command.py", line 540, in configure_images
    :      available = psutil.disk_usage(TMP_ROOT_MOUNTPOINT).free
    :    File "/home/amaury/.local/lib/python3.6/site-packages/psutil/__init__.py", line 2106, in disk_usage
    :      return _psplatform.disk_usage(path)
    :    File "/home/amaury/.local/lib/python3.6/site-packages/psutil/_psposix.py", line 131, in disk_usage
    :      st = os.statvfs(path)
    :  FileNotFoundError: [Errno 2] No such file or directory: '/media/amaury/root'

dts :  Please report that you are using:
    :  
    :  duckietown-shell-commands: 4.0.5
    :  python: "3.6.7 (default, Oct 22 2018, 11:32:17) \n[GCC 8.2.0]"
    :  duckietown-shell: 4.0.12
```

**Comment by AmaurX** [comment]
@aleksandarpetrov

**Comment by liampaull** [comment]
@AmaurX can you try just `dts init_sd_card` with no other options and tell me if it works?

**Comment by AmaurX** [comment]
@liampaull I tried and it gave the same error. I suspected my sd card to be tired and tried on another one with the full command and it work. Most probably the old one was tired of being mounted and unmounted and at some point of the process stopped showing up. 
So bottom line, I will get rid of this sd card and use a new one...
