### ISSUE TITLE
A bunch of ugly output on OSX python 3.7.7 

### ISSUE THREAD

**Issue by liampaull** [duckietown/duckietown-shell#63]
I get this whole brutal output every time I run a shell command:

```
➜  ~ dts --set-version daffy
INFO:dts:duckietown-shell 5.1.6

dts :  Problems with a command?
    :
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :
    :      Troubleshooting:
    :
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :
    :        (Note: you will have to re-configure.)
INFO:dts:Commands version: daffy
WARNING:dts:I cannot find the command path /Users/liam/.dt-shell/commands-multi/daffy
INFO:dts:Downloading commands in /Users/liam/.dt-shell/commands-multi/daffy ...
INFO:dts:duckietown-shell-commands 5.0.2
INFO:duckietown-challenges:duckietown-challenges 5.1.1
INFO:zj:zuper-ipce 5.1.2
INFO:zuper-typing:zuper-typing 5.0.12
INFO:zuper-commons:zuper-commons 5.0.7
INFO:duckietown-challenges:duckietown-challenges 5.1.1
INFO:zj:zuper-ipce 5.1.2
INFO:duckietown-challenges:duckietown-challenges 5.1.1
INFO:zj:zuper-ipce 5.1.2
INFO:duckietown-challenges:duckietown-challenges 5.1.1
INFO:zj:zuper-ipce 5.1.2
INFO:duckietown-challenges:duckietown-challenges 5.1.1
INFO:zj:zuper-ipce 5.1.2
INFO:duckietown-challenges:duckietown-challenges 5.1.1
INFO:zj:zuper-ipce 5.1.2
INFO:duckietown-challenges:duckietown-challenges 5.1.1
INFO:zj:zuper-ipce 5.1.2
INFO:duckietown-challenges:duckietown-challenges 5.1.1
INFO:zj:zuper-ipce 5.1.2
INFO:duckietown-challenges:duckietown-challenges 5.1.1
INFO:zj:zuper-ipce 5.1.2
INFO:duckietown-challenges:duckietown-challenges 5.1.1
INFO:zj:zuper-ipce 5.1.2
INFO:duckietown-challenges:duckietown-challenges 5.1.1
INFO:zj:zuper-ipce 5.1.2
ERROR:dts:


            !   Could not load commands.

                Cannot load command class 'challenges.evaluator.command.DTCommand' (package='challenges.', command='evaluator'): Traceback (most recent call last):
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 235, in _load_commands
    klass = _load_class(spec)
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 341, in _load_class
    mod = __import__(components[0])
  File "/Users/liam/.dt-shell/commands-multi/daffy/challenges/__init__.py", line 3, in <module>
    from duckietown_challenges import __version__
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/__init__.py", line 20, in <module>
    from .make_readmes import make_readmes_main as make_readmes_main
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/make_readmes.py", line 7, in <module>
    from .challenge import ChallengeDescription
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/challenge.py", line 9, in <module>
    from zuper_ipce import ipce_from_object, object_from_ipce
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/__init__.py", line 7, in <module>
    from .types import IPCE, TypeLike
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/types.py", line 4, in <module>
    from zuper_typing.annotations_tricks import is_Any
  File "/usr/local/lib/python3.7/site-packages/zuper_typing_z5-5.0.12-py3.7.egg/zuper_typing/__init__.py", line 24, in <module>
    from .debug_print_ import debug_print
  File "/usr/local/lib/python3.7/site-packages/zuper_typing_z5-5.0.12-py3.7.egg/zuper_typing/debug_print_.py", line 79, in <module>
    @dataclass
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1010, in dataclass
    return wrap(_cls)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1002, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 941, in _process_class
    globals=globals))
TypeError: _cmp_fn_loose() got an unexpected keyword argument 'globals'


Cannot load command class 'challenges.submit.command.DTCommand' (package='challenges.', command='submit'): Traceback (most recent call last):
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 235, in _load_commands
    klass = _load_class(spec)
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 341, in _load_class
    mod = __import__(components[0])
  File "/Users/liam/.dt-shell/commands-multi/daffy/challenges/__init__.py", line 3, in <module>
    from duckietown_challenges import __version__
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/__init__.py", line 20, in <module>
    from .make_readmes import make_readmes_main as make_readmes_main
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/make_readmes.py", line 7, in <module>
    from .challenge import ChallengeDescription
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/challenge.py", line 9, in <module>
    from zuper_ipce import ipce_from_object, object_from_ipce
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/__init__.py", line 8, in <module>
    from .constants import IEDO, IESO
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/constants.py", line 88, in <module>
    @dataclass
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1010, in dataclass
    return wrap(_cls)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1002, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 941, in _process_class
    globals=globals))
TypeError: _cmp_fn_loose() got an unexpected keyword argument 'globals'


Cannot load command class 'challenges.define.command.DTCommand' (package='challenges.', command='define'): Traceback (most recent call last):
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 235, in _load_commands
    klass = _load_class(spec)
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 341, in _load_class
    mod = __import__(components[0])
  File "/Users/liam/.dt-shell/commands-multi/daffy/challenges/__init__.py", line 3, in <module>
    from duckietown_challenges import __version__
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/__init__.py", line 20, in <module>
    from .make_readmes import make_readmes_main as make_readmes_main
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/make_readmes.py", line 7, in <module>
    from .challenge import ChallengeDescription
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/challenge.py", line 9, in <module>
    from zuper_ipce import ipce_from_object, object_from_ipce
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/__init__.py", line 8, in <module>
    from .constants import IEDO, IESO
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/constants.py", line 88, in <module>
    @dataclass
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1010, in dataclass
    return wrap(_cls)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1002, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 941, in _process_class
    globals=globals))
TypeError: _cmp_fn_loose() got an unexpected keyword argument 'globals'


Cannot load command class 'challenges.config.command.DTCommand' (package='challenges.', command='config'): Traceback (most recent call last):
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 235, in _load_commands
    klass = _load_class(spec)
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 341, in _load_class
    mod = __import__(components[0])
  File "/Users/liam/.dt-shell/commands-multi/daffy/challenges/__init__.py", line 3, in <module>
    from duckietown_challenges import __version__
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/__init__.py", line 20, in <module>
    from .make_readmes import make_readmes_main as make_readmes_main
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/make_readmes.py", line 7, in <module>
    from .challenge import ChallengeDescription
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/challenge.py", line 9, in <module>
    from zuper_ipce import ipce_from_object, object_from_ipce
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/__init__.py", line 8, in <module>
    from .constants import IEDO, IESO
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/constants.py", line 88, in <module>
    @dataclass
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1010, in dataclass
    return wrap(_cls)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1002, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 941, in _process_class
    globals=globals))
TypeError: _cmp_fn_loose() got an unexpected keyword argument 'globals'


Cannot load command class 'challenges.auth.command.DTCommand' (package='challenges.', command='auth'): Traceback (most recent call last):
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 235, in _load_commands
    klass = _load_class(spec)
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 341, in _load_class
    mod = __import__(components[0])
  File "/Users/liam/.dt-shell/commands-multi/daffy/challenges/__init__.py", line 3, in <module>
    from duckietown_challenges import __version__
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/__init__.py", line 20, in <module>
    from .make_readmes import make_readmes_main as make_readmes_main
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/make_readmes.py", line 7, in <module>
    from .challenge import ChallengeDescription
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/challenge.py", line 9, in <module>
    from zuper_ipce import ipce_from_object, object_from_ipce
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/__init__.py", line 8, in <module>
    from .constants import IEDO, IESO
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/constants.py", line 88, in <module>
    @dataclass
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1010, in dataclass
    return wrap(_cls)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1002, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 941, in _process_class
    globals=globals))
TypeError: _cmp_fn_loose() got an unexpected keyword argument 'globals'


Cannot load command class 'challenges.follow.command.DTCommand' (package='challenges.', command='follow'): Traceback (most recent call last):
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 235, in _load_commands
    klass = _load_class(spec)
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 341, in _load_class
    mod = __import__(components[0])
  File "/Users/liam/.dt-shell/commands-multi/daffy/challenges/__init__.py", line 3, in <module>
    from duckietown_challenges import __version__
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/__init__.py", line 20, in <module>
    from .make_readmes import make_readmes_main as make_readmes_main
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/make_readmes.py", line 7, in <module>
    from .challenge import ChallengeDescription
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/challenge.py", line 9, in <module>
    from zuper_ipce import ipce_from_object, object_from_ipce
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/__init__.py", line 8, in <module>
    from .constants import IEDO, IESO
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/constants.py", line 88, in <module>
    @dataclass
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1010, in dataclass
    return wrap(_cls)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1002, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 941, in _process_class
    globals=globals))
TypeError: _cmp_fn_loose() got an unexpected keyword argument 'globals'


Cannot load command class 'challenges.reset.command.DTCommand' (package='challenges.', command='reset'): Traceback (most recent call last):
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 235, in _load_commands
    klass = _load_class(spec)
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 341, in _load_class
    mod = __import__(components[0])
  File "/Users/liam/.dt-shell/commands-multi/daffy/challenges/__init__.py", line 3, in <module>
    from duckietown_challenges import __version__
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/__init__.py", line 20, in <module>
    from .make_readmes import make_readmes_main as make_readmes_main
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/make_readmes.py", line 7, in <module>
    from .challenge import ChallengeDescription
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/challenge.py", line 9, in <module>
    from zuper_ipce import ipce_from_object, object_from_ipce
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/__init__.py", line 8, in <module>
    from .constants import IEDO, IESO
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/constants.py", line 88, in <module>
    @dataclass
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1010, in dataclass
    return wrap(_cls)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1002, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 941, in _process_class
    globals=globals))
TypeError: _cmp_fn_loose() got an unexpected keyword argument 'globals'


Cannot load command class 'challenges.info.command.DTCommand' (package='challenges.', command='info'): Traceback (most recent call last):
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 235, in _load_commands
    klass = _load_class(spec)
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 341, in _load_class
    mod = __import__(components[0])
  File "/Users/liam/.dt-shell/commands-multi/daffy/challenges/__init__.py", line 3, in <module>
    from duckietown_challenges import __version__
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/__init__.py", line 20, in <module>
    from .make_readmes import make_readmes_main as make_readmes_main
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/make_readmes.py", line 7, in <module>
    from .challenge import ChallengeDescription
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/challenge.py", line 9, in <module>
    from zuper_ipce import ipce_from_object, object_from_ipce
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/__init__.py", line 8, in <module>
    from .constants import IEDO, IESO
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/constants.py", line 88, in <module>
    @dataclass
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1010, in dataclass
    return wrap(_cls)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1002, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 941, in _process_class
    globals=globals))
TypeError: _cmp_fn_loose() got an unexpected keyword argument 'globals'


Cannot load command class 'challenges.evaluate.command.DTCommand' (package='challenges.', command='evaluate'): Traceback (most recent call last):
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 235, in _load_commands
    klass = _load_class(spec)
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 341, in _load_class
    mod = __import__(components[0])
  File "/Users/liam/.dt-shell/commands-multi/daffy/challenges/__init__.py", line 3, in <module>
    from duckietown_challenges import __version__
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/__init__.py", line 20, in <module>
    from .make_readmes import make_readmes_main as make_readmes_main
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/make_readmes.py", line 7, in <module>
    from .challenge import ChallengeDescription
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/challenge.py", line 9, in <module>
    from zuper_ipce import ipce_from_object, object_from_ipce
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/__init__.py", line 8, in <module>
    from .constants import IEDO, IESO
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/constants.py", line 88, in <module>
    @dataclass
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1010, in dataclass
    return wrap(_cls)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1002, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 941, in _process_class
    globals=globals))
TypeError: _cmp_fn_loose() got an unexpected keyword argument 'globals'


Cannot load command class 'challenges.list.command.DTCommand' (package='challenges.', command='list'): Traceback (most recent call last):
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 235, in _load_commands
    klass = _load_class(spec)
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 341, in _load_class
    mod = __import__(components[0])
  File "/Users/liam/.dt-shell/commands-multi/daffy/challenges/__init__.py", line 3, in <module>
    from duckietown_challenges import __version__
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/__init__.py", line 20, in <module>
    from .make_readmes import make_readmes_main as make_readmes_main
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/make_readmes.py", line 7, in <module>
    from .challenge import ChallengeDescription
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/challenge.py", line 9, in <module>
    from zuper_ipce import ipce_from_object, object_from_ipce
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/__init__.py", line 8, in <module>
    from .constants import IEDO, IESO
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/constants.py", line 88, in <module>
    @dataclass
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1010, in dataclass
    return wrap(_cls)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1002, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 941, in _process_class
    globals=globals))
TypeError: _cmp_fn_loose() got an unexpected keyword argument 'globals'


Cannot load command class 'challenges.retire.command.DTCommand' (package='challenges.', command='retire'): Traceback (most recent call last):
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 235, in _load_commands
    klass = _load_class(spec)
  File "/Users/liam/Library/Python/3.7/lib/python/site-packages/dt_shell/cli.py", line 341, in _load_class
    mod = __import__(components[0])
  File "/Users/liam/.dt-shell/commands-multi/daffy/challenges/__init__.py", line 3, in <module>
    from duckietown_challenges import __version__
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/__init__.py", line 20, in <module>
    from .make_readmes import make_readmes_main as make_readmes_main
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/make_readmes.py", line 7, in <module>
    from .challenge import ChallengeDescription
  File "/usr/local/lib/python3.7/site-packages/duckietown_challenges/challenge.py", line 9, in <module>
    from zuper_ipce import ipce_from_object, object_from_ipce
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/__init__.py", line 8, in <module>
    from .constants import IEDO, IESO
  File "/usr/local/lib/python3.7/site-packages/zuper_ipce/constants.py", line 88, in <module>
    @dataclass
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1010, in dataclass
    return wrap(_cls)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1002, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 941, in _process_class
    globals=globals))
TypeError: _cmp_fn_loose() got an unexpected keyword argument 'globals'


            !   To recover, you might want to delete the directory
            !
            !      ~/.dt-shell/commands
            !
            !
```

**Comment by afdaniele** [comment]
I reported this to @AndreaCensi before and he fixed it already, he knows what it is.

**Comment by AndreaCensi** [comment]
@liampaull 

It's some dependency - can you run for me `pip list`?

**Comment by liampaull** [comment]
```Package                      Version  Location
---------------------------- -------- -----------------------------------------------------------------------------------------------------------
appdirs                      1.4.3
appnope                      0.1.0
attrs                        19.1.0
backcall                     0.1.0
base58                       1.0.3
beautifulsoup4               4.8.1
bleach                       3.1.0
bqplot                       0.11.8
carnivalmirror               0.6.2
cbor2                        4.1.2
certifi                      2019.3.9
chardet                      3.0.4
cloudpickle                  1.2.1
compmake                     4.0.3
comptests                    1.4.34
ConfTools                    1.9.9
coverage                     5.0b1
cycler                       0.10.0
dataclasses                  0.6
DecentLogs                   1.4.0
decorator                    4.4.0
defusedxml                   0.6.0
distlib                      0.3.0
docker                       3.7.2
docker-pycreds               0.4.0
docutils                     0.15.2
duckietown-challenges        4.0.30
duckietown-challenges-daffy  5.1.1
duckietown-gym-daffy         5.0.12   /Users/liam/duckietown/dt-env-developer/aido/challenge-aido_LF-baseline-duckietown/1_develop/simulation/src
duckietown-serialization-ds1 1.0.7
duckietown-shell             5.1.6
duckietown-world-daffy       5.0.10
ecdsa                        0.13
entrypoints                  0.3
filelock                     3.0.12
frozendict                   1.2
future                       0.17.1
gitdb2                       2.0.5
GitPython                    2.1.11
gym                          0.14.0
idna                         2.8
ifaddr                       0.1.6
imageio                      2.6.1
importlib-metadata           1.5.0
ipykernel                    5.1.1
ipython                      7.7.0
ipython-genutils             0.2.0
ipywidgets                   7.5.1
jedi                         0.14.1
Jinja2                       2.10.1
json5                        0.8.5
jsonschema                   3.0.1
junit-xml                    1.8
jupyros                      0.2.2
jupyter-client               5.3.1
jupyter-core                 4.5.0
jupyterlab                   1.0.4
jupyterlab-server            1.0.0
kiwisolver                   1.1.0
lxml                         4.4.1
Markdown                     3.1.1
MarkupSafe                   1.1.1
matplotlib                   3.2.0rc1
mistune                      0.8.4
mypy-extensions              0.4.3
nbconvert                    5.5.0
nbformat                     4.4.0
networkx                     2.2
nose                         1.3.7
notebook                     6.0.0
numpy                        1.16.2
opencv-python                4.1.1.26
oyaml                        0.9
pandas                       0.25.1
pandocfilters                1.4.2
parso                        0.5.1
pexpect                      4.7.0
pickleshare                  0.7.5
Pillow                       6.2.1
pip                          20.0.2
plotly                       4.3.0
prometheus-client            0.7.1
prompt-toolkit               2.0.9
psutil                       5.6.1
ptyprocess                   0.6.0
pybase64                     1.0.1
PyContracts                  1.8.12
PyGeometry                   1.5.6
pyglet                       1.3.2
Pygments                     2.4.2
pyparsing                    2.4.5
pyrsistent                   0.15.4
python-dateutil              2.8.0
pytz                         2019.2
PyWavelets                   1.1.1
PyYAML                       5.1
pyzmq                        18.0.2
QuickApp                     1.3.19
reprep                       3.0.0
requests                     2.21.0
retrying                     1.3.3
scikit-image                 0.16.2
scipy                        1.3.0
Send2Trash                   1.5.0
setproctitle                 1.1.10
setuptools                   46.0.0
six                          1.12.0
smmap2                       2.0.5
soupsieve                    1.9.5
svgwrite                     1.3.1
SystemCmd                    3.0.1
termcolor                    1.1.0
terminado                    0.8.2
testpath                     0.4.2
texttable                    1.6.1
tornado                      6.0.3
traitlets                    4.3.2
traittypes                   0.2.1
typing-extensions            3.7.4.1
urllib3                      1.24.1
validate-email               1.3
virtualenv                   20.0.9
wcwidth                      0.1.7
webencodings                 0.5.1
websocket-client             0.56.0
wheel                        0.34.2
whichcraft                   0.5.2
widgetsnbextension           3.5.1
xtermcolor                   1.3
zeroconf                     0.23.0
zipp                         3.1.0
zuper-commons-z5             5.0.7
zuper-ipce-z5                5.1.2
zuper-typing-z5              5.0.12```

**Comment by liampaull** [comment]
@afdaniele not fixed
