### ISSUE TITLE
Duckietown Shell on Windows

### ISSUE THREAD

**Issue by david-boles** [duckietown/duckietown-shell#66]
Hello, here from the Brown Duckiesky team. We have a number of members who have Windows computers and would like to edit our duckumentation locally, is that not supported? Installing docker at all on windows 10 home seems to be impossible in some cases (when Microsoft doesn't allow the may 2004/19041 update to be installed yet on particular hardware) and even when it is, dts crashes due to a missing library that seems to be Unix-specific:
```
INFO:dts:duckietown-shell 5.1.6
Traceback (most recent call last):
  File "C:\Users\111\AppData\Roaming\Python\Python38\Scripts\dts-script.py", line 11, in <module>
    load_entry_point('duckietown-shell==5.1.6', 'console_scripts', 'dts')()
  File "c:\users\111\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\111\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "c:\users\111\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "c:\users\111\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\111\AppData\Roaming\Python\Python38\site-packages\dt_shell\__init__.py", line 37, in <module>
    from .main import cli_main
  File "C:\Users\111\AppData\Roaming\Python\Python38\site-packages\dt_shell\main.py", line 15, in <module>
    from .env_checks import abort_if_running_with_sudo
  File "C:\Users\111\AppData\Roaming\Python\Python38\site-packages\dt_shell\env_checks.py", line 1, in <module>
    import grp
ModuleNotFoundError: No module named 'grp'
```
We also tried using the docker image dts alias from  bash and got:
```
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
```
I'm not experienced enough with docker to determine what that error is/where it's coming from. Is all this expected? Anything else we should try before just using a VM? Thanks.

**Comment by jasonhu5** [comment]
For the TTY issue, you may also try using the docker dts from within PowerShell.

**Comment by david-boles** [comment]
@jasonhu5 Thanks, we'll give that a shot.

**Comment by david-boles** [comment]
@jasonhu5 that got a little bit further with those who are able to install Docker but now stuck due to #67.

**Comment by AndreaCensi** [comment]
@david-boles we haven't tried very much things on windows. @afdaniele is the main developer of the shell, you might want to tag him when you have these problems. (and/or ping on Slack)
