### ISSUE TITLE
While submitting a challenge

### ISSUE THREAD

**Issue by iamkashish** [duckietown/duckietown-shell#83]
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.0.97 path /home/hackercosmos/.local/lib/python3.8/site-packages

dts :  Traceback (most recent call last):
    :    File "/home/hackercosmos/.local/lib/python3.8/site-packages/dt_shell/main.py", line 39, in cli_main
    :      cli_main_()
    :    File "/home/hackercosmos/.local/lib/python3.8/site-packages/dt_shell/main.py", line 197, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/hackercosmos/.local/lib/python3.8/site-packages/dt_shell/cli.py", line 278, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/hackercosmos/.local/lib/python3.8/site-packages/dt_shell/dt_command_abs.py", line 48, in do_command
    :      cls.command(shell, args)
    :    File "/home/hackercosmos/.dt-shell/commands-multi/daffy/challenges/command.py", line 17, in command
    :      check_package_version("duckietown-docker-utils-daffy", "6.0.78")
    :    File "/home/hackercosmos/.local/lib/python3.8/site-packages/dt_shell/package_version_check.py", line 47, in check_package_version
    :      installed = _get_installed_distributions()
    :    File "/home/hackercosmos/.local/lib/python3.8/site-packages/dt_shell/package_version_check.py", line 14, in _get_installed_distributions
    :      from pip._internal.metadata import get_environment
    :  ModuleNotFoundError: No module named 'pip._internal.metadata'
WARNING:dts:Please update "pip" to have better debug info.

dts :  To report a bug, please also include the contents of /home/hackercosmos/shell-debug-info.txt

----------------------------------------------------------------------------------------------------------------------------------------------------------------------
And file shell-debug-info.txt contains:
commands-version: daffy
duckietown-shell: 5.2.19
duckietown-shell-commands: 5.4.5
encodings:
  locale: UTF-8
  stderr: utf-8
  stdout: utf-8
python: "3.8.10 (default, Nov 26 2021, 20:14:08) \n[GCC 9.3.0]"

**Comment by iamkashish** [comment]
This is a pip configuration problem.
Update and upgrade pip and pip3
```
pip3 --install --user -U pip
pip install --user -U pip
```
