### ISSUE TITLE
Error while updating duckiebot

### ISSUE THREAD

**Issue by asal97** [duckietown/duckietown-shell#87]
Hi, I wanted to update my duckiebot and i got the following error in doing so: 

```
uit@uit-HP:~$` dts duckiebot update DT05

dts :  Problems with a command?
    :  
    :      Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :      Troubleshooting:
    :  
    :      - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :      - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :        (Note: you will have to re-configure.)
INFO:dts:Commands version: daffy
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.0.97 path /home/uit/.local/lib/python3.8/site-packages
INFO:dts:Fetching list of containers...
INFO:dts:Removing 0 containers.
INFO:dts:Fetching list of images...
INFO:dts:Removing 0 images.
INFO:dts:Nothing to do
WARNING:dts:Cannot find 'docker.io' in available config credentials.
I have credentials for []
Use:
  dts challenges config --docker-server ... --docker-username ... --docker-password ...

for each of the servers
WARNING:dts:I will try to continue because raise_on_error = False.
INFO:dts:Waiting for device "DT05"...
INFO:dts:Detected device type is "duckiebot".
INFO:dts:Retrieving info about Docker endpoint...
INFO:dts:Detected device architecture is "arm64v8".
INFO:dts:Pulling image `portainer/portainer:1.24.1-alpine`...

dts :  Traceback (most recent call last):
    :    File "/usr/lib/python3/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    :      response.raise_for_status()
    :    File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    :      raise HTTPError(http_error_msg, response=self)
    :  requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://dt05.local:2375/v1.35/images/create?tag=1.24.1-alpine&fromImage=portainer%2Fportainer
    :  
    :  During handling of the above exception, another exception occurred:
    :  
    :  Traceback (most recent call last):
    :    File "/home/uit/.local/lib/python3.8/site-packages/dt_shell/main.py", line 39, in cli_main
    :      cli_main_()
    :    File "/home/uit/.local/lib/python3.8/site-packages/dt_shell/main.py", line 197, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/uit/.local/lib/python3.8/site-packages/dt_shell/cli.py", line 278, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/uit/.local/lib/python3.8/site-packages/dt_shell/dt_command_abs.py", line 41, in do_command
    :      cls.commands[word].do_command(cls.commands[word], shell, " ".join(parts[1:]))
    :    File "/home/uit/.local/lib/python3.8/site-packages/dt_shell/dt_command_abs.py", line 48, in do_command
    :      cls.command(shell, args)
    :    File "/home/uit/.dt-shell/commands-multi/daffy/duckiebot/update/command.py", line 63, in command
    :      success = shell.include.stack.up.command(
    :    File "/home/uit/.dt-shell/commands-multi/daffy/stack/up/command.py", line 112, in command
    :      pull_image(image_name, parsed.machine)
    :    File "/home/uit/.dt-shell/commands-multi/daffy/utils/docker_utils.py", line 226, in pull_image
    :      for line in client.api.pull(image, stream=True, decode=True):
    :    File "/usr/lib/python3/dist-packages/docker/api/image.py", line 415, in pull
    :      self._raise_for_status(response)
    :    File "/usr/lib/python3/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    :      raise create_api_error_from_http_exception(e)
    :    File "/usr/lib/python3/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    :      raise cls(e, response=response, explanation=explanation)
    :  docker.errors.APIError: 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.53:53: read udp 127.0.0.1:58905->127.0.0.53:53: i/o timeout")
```

I can ping the bot and i am also connected to the internet. I am not sure what is the problem here.

**Comment by afdaniele** [comment]
It's a caching issue on the DNS, keep trying and it'll work eventually. If it persists, let us know.

**Comment by asal97** [comment]
I flushed the dns cache using 
'sudo systemd-resolve --flush-caches'
and tried the update command around 10 times again. However the problem still persist.

**Comment by asal97** [comment]
I tried flushing DNS cache using `sudo systemd-resolve --flush-caches` and tried the update command around 10 time again. However the problem still persist.

**Comment by afdaniele** [comment]
Can you run this from your robot?
```ping 8.8.8.8```

**Comment by asal97** [comment]
I have 100% packet loss while pinging it from the duckiebot : 

`uit@uit-HP:~$ ssh duckie@DT05.local `

```duckie@DT05:~$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
^C
--- 8.8.8.8 ping statistics ---
129 packets transmitted, 0 received, 100% packet loss, time 131062ms
```

**Comment by asal97** [comment]
Yes I can (without any packet loss)
