### ISSUE TITLE
Error dts: Could not load commands

### ISSUE THREAD

**Issue by tnacho-23** [duckietown/duckietown-shell#96]
Hi!
I've been having some troubles with the installation of the duckietown shell. I am following the instructions of the webpage (https://docs.duckietown.com/daffy/opmanual-duckiebot/setup/setup_account/duckietown_accounts.html) and, when i run the  command for setting the duckietown token i get the following error (it's too long, i couldn't paste it all):

```shell
ignacio@ignacio-Lenovo-G40-80:~$ dts tok set
Duckietown Shell (v5.5.9)
INFO:dts:Commands version: daffy
INFO:dts:Checking for updates in the Duckietown shell commands repo...
INFO:dts:Duckietown shell commands are up-to-date.
=========================================

    Patience is the virtue of strong!

=========================================
DEBUG:duckietown_docker_utils:duckietown_docker_utils version 6.1.1 path /home/ignacio/.local/lib/python3.10/site-packages
/home/ignacio/.local/lib/python3.10/site-packages/pydantic/_internal/_config.py:257: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
ERROR:dts:


            !   Could not load commands.

                Cannot load command class 'start_gui_tools.command.DTCommand' (package='', command='start_gui_tools'): Traceback (most recent call last):
  File "/home/ignacio/.local/lib/python3.10/site-packages/dt_shell/cli.py", line 238, in _load_commands
    klass = _load_class(spec)
  File "/home/ignacio/.local/lib/python3.10/site-packages/dt_shell/cli.py", line 371, in _load_class
    mod = __import__(components[0])
  File "/home/ignacio/.dt-shell/commands-multi/daffy/start_gui_tools/__init__.py", line 2, in <module>
    from .command import DTCommand
  File "/home/ignacio/.dt-shell/commands-multi/daffy/start_gui_tools/command.py", line 14, in <module>
    from utils.docker_utils import (
  File "/home/ignacio/.dt-shell/commands-multi/daffy/utils/docker_utils.py", line 630, in <module>
    import dockertown
  File "/home/ignacio/.local/lib/python3.10/site-packages/dockertown/__init__.py", line 4, in <module>
    from .components.buildx.cli_wrapper import Builder
  File "/home/ignacio/.local/lib/python3.10/site-packages/dockertown/components/buildx/cli_wrapper.py", line 10, in <module>
    from ...components.image.cli_wrapper import Image, ImageCLI
  File "/home/ignacio/.local/lib/python3.10/site-packages/dockertown/components/image/cli_wrapper.py", line 17, in <module>
    from ...components.container import cli_wrapper as container_cli_wrapper
  File "/home/ignacio/.local/lib/python3.10/site-packages/dockertown/components/container/cli_wrapper.py", line 13, in <module>
    from ...components.network import cli_wrapper as network_cli_wrapper
  File "/home/ignacio/.local/lib/python3.10/site-packages/dockertown/components/network/cli_wrapper.py", line 9, in <module>
    from .models import NetworkContainer, NetworkInspectResult, NetworkIPAM
  File "/home/ignacio/.local/lib/python3.10/site-packages/dockertown/components/network/models.py", line 8, in <module>
    class NetworkIPAM(DockerCamelModel):
  File "/home/ignacio/.local/lib/python3.10/site-packages/dockertown/utils.py", line 348, in all_fields_optional
    field.required = False
AttributeError: 'FieldInfo' object has no attribute 'required'

.
.
.
.

Cannot load command class 'stack.up.command.DTCommand' (package='stack.', command='up'): Traceback (most recent call last):
  File "/home/ignacio/.local/lib/python3.10/site-packages/dt_shell/cli.py", line 238, in _load_commands
    klass = _load_class(spec)
  File "/home/ignacio/.local/lib/python3.10/site-packages/dt_shell/cli.py", line 371, in _load_class
    mod = __import__(components[0])
  File "/home/ignacio/.dt-shell/commands-multi/daffy/stack/__init__.py", line 47, in <module>
    exec("from .%s import *" % _basename(_mod))
  File "<string>", line 1, in <module>
  File "/home/ignacio/.dt-shell/commands-multi/daffy/stack/pull/__init__.py", line 21, in <module>
    from .command import *
  File "/home/ignacio/.dt-shell/commands-multi/daffy/stack/pull/command.py", line 9, in <module>
    from utils.docker_utils import DEFAULT_MACHINE, get_endpoint_architecture, get_registry_to_use, pull_image
  File "/home/ignacio/.dt-shell/commands-multi/daffy/utils/docker_utils.py", line 630, in <module>
    import dockertown
  File "/home/ignacio/.local/lib/python3.10/site-packages/dockertown/__init__.py", line 4, in <module>
    from .components.buildx.cli_wrapper import Builder
  File "/home/ignacio/.local/lib/python3.10/site-packages/dockertown/components/buildx/cli_wrapper.py", line 10, in <module>
    from ...components.image.cli_wrapper import Image, ImageCLI
  File "/home/ignacio/.local/lib/python3.10/site-packages/dockertown/components/image/cli_wrapper.py", line 17, in <module>
    from ...components.container import cli_wrapper as container_cli_wrapper
  File "/home/ignacio/.local/lib/python3.10/site-packages/dockertown/components/container/cli_wrapper.py", line 13, in <module>
    from ...components.network import cli_wrapper as network_cli_wrapper
  File "/home/ignacio/.local/lib/python3.10/site-packages/dockertown/components/network/cli_wrapper.py", line 9, in <module>
    from .models import NetworkContainer, NetworkInspectResult, NetworkIPAM
  File "/home/ignacio/.local/lib/python3.10/site-packages/dockertown/components/network/models.py", line 8, in <module>
    class NetworkIPAM(DockerCamelModel):
  File "/home/ignacio/.local/lib/python3.10/site-packages/dockertown/utils.py", line 348, in all_fields_optional
    field.required = False
AttributeError: 'FieldInfo' object has no attribute 'required'


            !   To recover, you might want to delete the directory
            !
            !      ~/.dt-shell/commands
            !
            !


ts :  args: []

Please enter your Duckietown token.

It looks something like this:

    dt1-7vEuJsaxeXXXXX-43dzqWFnWd8KBa1yev1g3UKnzVxZkkTbfSJnxzuJjWaANeMf4y6XSXBWTpJ7vWXXXX

To find your token, first login to duckietown.org, and open the page:

    https://www.duckietown.org/site/your-token


Enter token: 

``` 
As you can see, i can put my token after the error, but it seems a bit strange. 
Also, after that, i continue having the same error everytime i write a dts command.

I've already checked the other issues with similar problems but nothing seems to work.

(After finishing the installation and ignoring all errors, I haven't tested if it works with a duckiebot yet, I'll try tomorrow and update with more info).

Thanks!

**Comment by tnacho-23** [comment]
Update: It doesn´t work with de duckiebot. The only command that the shell recognizes is 
```shell
dts fleet discover
``` 

Other commands (keyboard_control, for example), launch the same error mentioned above plus:

```shell
.
.
.

!   To recover, you might want to delete the directory
            !
            !      ~/.dt-shell/commands
            !
            !

            
Command `keyboard_control` not recognized.
Available sub-commands are:

	battery
	support
``` 

Thanks!

**Comment by rickshoe2** [comment]
I am havingthe same error!

**Comment by tnacho-23** [comment]
**[SOLVED]**
Was solved by running the command:

```shell
pip3 install -U dockertown>=0.2.3
``` 

Thanks to the duckietown team on Slack for the help! :D

**Comment by afdaniele** [comment]
This is now fixed!
